DROP TABLE IF EXISTS memo;

CREATE TABLE memo (
  id int PRIMARY KEY AUTO_INCREMENT,
  title text NOT NULL,
  body text NOT NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT = 'memo';
